#!/usr/bin/env python3
"""
Responsive image pipeline for the site in /site.

Reads every original in site/photos/ and writes, into site/assets/img/:
  <name>-<width>.webp for each target width (never upscaled past the
  original), one <name>-<width>.jpg fallback at the width nearest 1200px
  for the <img src> of the few browsers without WebP, plus og-<name>.jpg (1200x630) for
  photos listed in OG_CROPS.

It also writes site/data/images.json — the width/height of each original and
the widths generated — which the build reads to emit correct srcset, width
and height attributes (no layout shift).

The outputs are committed, so the Netlify build itself needs only Node.
Run after adding or replacing a photo:

    pip install pillow
    python3 tools/site-images.py

To add a real project photo: drop it into site/photos/ with a descriptive,
hyphenated filename (e.g. vilamoura-villa-exterior-after.jpg), run this
script, then reference it by that name (without extension) in
site/data/projects.js or anywhere else that takes an image key.
"""
import json
import os
import sys

from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "site", "photos")
OUT = os.path.join(ROOT, "site", "assets", "img")
MANIFEST = os.path.join(ROOT, "site", "data", "images.json")

WIDTHS = [480, 800, 1200, 1600, 2000]
WEBP_Q = 78
JPG_Q = 80

# Art-directed crops: extra variants cut from an original, published under
# their own key (<name>-<suffix>). (suffix, width/height ratio, horizontal
# focus 0-1). The homepage hero uses a 9:16 portrait crop on phones so a
# small screen downloads a small file instead of a wide landscape.
CROPS = {
    "algarve-villa-exterior-freshly-painted": [("portrait", 9 / 16, 0.64)],
}

# Photos that also get a 1200x630 OpenGraph crop, with the vertical focus
# point (0 = top, 1 = bottom) used for the crop.
OG_CROPS = {
    "algarve-villa-exterior-freshly-painted": 0.45,
}


def main():
    os.makedirs(OUT, exist_ok=True)
    # site/assets/img is entirely generated by this script: clear it so a
    # renamed or removed photo does not leave orphaned variants behind.
    for old in os.listdir(OUT):
        if old.endswith((".webp", ".jpg")):
            os.remove(os.path.join(OUT, old))
    manifest = {}
    names = sorted(f for f in os.listdir(SRC) if f.lower().endswith((".jpg", ".jpeg", ".png", ".webp")))
    if not names:
        print("No photos in", SRC)
        sys.exit(1)
    for fname in names:
        name = os.path.splitext(fname)[0]
        im = ImageOps.exif_transpose(Image.open(os.path.join(SRC, fname))).convert("RGB")
        w, h = im.size
        # Every standard width comfortably below the original, plus the
        # original itself — never an upscale, never two near-identical files.
        widths = [x for x in WIDTHS if x < w * 0.95] + [w]
        fallback = min(widths, key=lambda x: abs(x - 1200))
        for tw in widths:
            th = round(h * tw / w)
            r = im.resize((tw, th), Image.LANCZOS) if tw != w else im
            r.save(os.path.join(OUT, f"{name}-{tw}.webp"), "WEBP", quality=WEBP_Q, method=6)
            if tw == fallback:
                r.save(os.path.join(OUT, f"{name}-{tw}.jpg"), "JPEG", quality=JPG_Q, optimize=True, progressive=True)
        if name in OG_CROPS:
            focus = OG_CROPS[name]
            target = 1200 / 630
            if w / h > target:
                cw, ch = round(h * target), h
                box = ((w - cw) // 2, 0, (w - cw) // 2 + cw, ch)
            else:
                cw, ch = w, round(w / target)
                top = int(max(0, min(h - ch, focus * h - ch / 2)))
                box = (0, top, cw, top + ch)
            im.crop(box).resize((1200, 630), Image.LANCZOS).save(
                os.path.join(OUT, f"og-{name}.jpg"), "JPEG", quality=84, optimize=True, progressive=True)
        manifest[name] = {"width": w, "height": h, "widths": widths, "fallback": fallback}
        for suffix, ratio, fx in CROPS.get(name, []):
            cw = min(w, round(h * ratio))
            left = int(max(0, min(w - cw, fx * w - cw / 2)))
            crop = im.crop((left, 0, left + cw, h))
            key = f"{name}-{suffix}"
            cws = [x for x in WIDTHS if x < cw * 0.95] + [cw]
            cfb = min(cws, key=lambda x: abs(x - 1200))
            for tw in cws:
                r = crop.resize((tw, round(h * tw / cw)), Image.LANCZOS) if tw != cw else crop
                r.save(os.path.join(OUT, f"{key}-{tw}.webp"), "WEBP", quality=WEBP_Q, method=6)
                if tw == cfb:
                    r.save(os.path.join(OUT, f"{key}-{tw}.jpg"), "JPEG", quality=JPG_Q, optimize=True, progressive=True)
            manifest[key] = {"width": cw, "height": h, "widths": cws, "fallback": cfb}
            print(f"  crop {key}: {cw}x{h} -> {cws}")
        print(f"{name}: {w}x{h} -> {widths}")
    with open(MANIFEST, "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")


if __name__ == "__main__":
    main()
